# Generated by Django 5.1.3 on 2024-12-19 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='mark',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
